#!/bin/sh

picom --experimental-backends &
fcitx5 &
clipmenud  &
xrdb merge ~/.config/x11/Xresources_catppuccin &
hsetroot -fill ~/personal/pictures/wall.png &
xbanish -t 1 -s &
# run bar script and dwm ( do not remove this )
~/.config/iamchad/scripts/bar.sh &
dwm
