#!/bin/sh

fcitx5 &
picom --experimental-backends &
xrdb merge ~/.config/x11/Xresources_catppuccin &
feh --no-fehbg --bg-fill ~/personal/pictures/wall.png &

# run bar script and dwm ( do not remove this )
~/.config/iamchad/scripts/bar.sh &
dwm
